name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Run clippy (all features)
        run: |
          cargo clippy

      - name: Run unit tests
        run: |
          cargo test --all-targets

  build-msrv:
    name: Test on MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.56.1
      - name: Run unit tests
        run: cargo test --all-targets

  build-nostd:
    name: Build on no_std target (riscv32imc-esp-espidf)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: riscv32imc-esp-espidf
          components: rustc, cargo
      - run: cargo build --target riscv32imc-esp-espidf --lib --release --no-default-features
