name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Run clippy (all features)
        run: |
          cargo clippy

      - name: Run unit tests
        run: |
          cargo test --all-targets

  build-msrv:
    name: Test on MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.56.1
      - name: Run unit tests
        run: cargo test --all-targets

  build-nostd:
    # wasm32-unknown-emscripten is no_std, and it is supported by getrandom
    name: Build on no_std target (wasm32-unknown-emscripten)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-emscripten
      - run: cargo build --target wasm32-unknown-emscripten --lib --release
